services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    command:
      make test
    image: cirarius/docker-project-74
    depends_on: 
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5