FROM node:20.12

WORKDIR /app

COPY app/package*.json ./

RUN apt update  --no-install-recommends && apt-get install -y apt-transport-https ca-certificates sqlite3 build-essential --no-install-recommends

RUN npm ci

COPY app .

ENV NODE_ENV=production
ENV PORT=8080

RUN make build
