FROM node:20.12

WORKDIR /app

COPY app/package*.json ./

RUN apt update --no-install-recommends && apt-get install -y apt-transport-https=2.6.1 ca-certificates sqlite3 build-essential=12.9 --no-install-recommends

RUN npm ci

COPY app .

ENV NODE_ENV=production
ENV PORT=8080

RUN make build
