services:
  app:
    build:
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
    command:
      make start

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile